[versions]
dbinspector = "5.3.0"
gradle = "4.1.3"
kotlin = "1.4.32"
coroutines = "1.4.3"
core = "1.3.2"
appcompat = "1.2.0"
activity = "1.2.2"
fragment = "1.3.2"
lifecycle = "2.3.1"
viewpager = "1.0.0"
paging = "3.0.0-beta03"
recyclerview = "1.2.0"
startup = "1.0.0"
swiperefresh = "1.1.0"
datastore = "1.0.0-alpha08"
dynamicanimation = "1.0.0"
design = "1.3.0"
protobuf-core = "3.15.8"
protobuf-plugin = "0.8.15"
koin = "3.0.1-beta-2"
fuzzy = "1.3.1"
detekt = "1.16.0"
ktlint = "10.0.0"
cpd = "3.1"
dokka = "1.4.30"

[libraries]
library = { module = "com.infinum.dbinspector:dbinspector", version.ref = "dbinspector" }
librarynoop = { module = "com.infinum.dbinspector:dbinspector-no-op", version.ref = "dbinspector" }

gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }

kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-core = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

androidx-core = { module = "androidx.core:core-ktx", version.ref = "core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
androidx-lifecycle-viewmodel = {module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-viewpager = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-paging = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }
androidx-swiperefresh = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefresh" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "startup" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
androidx-dynamicanimation = { module = "androidx.dynamicanimation:dynamicanimation", version.ref = "dynamicanimation" }

material = { module = "com.google.android.material:material", version.ref = "design" }

protobuf-artifact = { module = "com.google.protobuf:protoc", version.ref = "protobuf-core" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf-core" }
protobuf-plugin = { module = "com.google.protobuf:protobuf-gradle-plugin", version.ref = "protobuf-plugin" }

koin = { module = "io.insert-koin:koin-android", version.ref = "koin" }

fuzzy = { module = "me.xdrop:fuzzywuzzy", version.ref = "fuzzy" }

detekt-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint" }

cpd = { module = "de.aaschmid:gradle-cpd-plugin", version.ref = "cpd" }

dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }

[bundles]
androidx = [
    "androidx-core",
    "androidx-appcompat",
    "androidx-activity",
    "androidx-fragment",
    "androidx-lifecycle-viewmodel",
    "androidx-viewpager",
    "androidx-recyclerview",
    "androidx-paging",
    "androidx-swiperefresh",
    "androidx-startup",
    "androidx-datastore",
    "androidx-dynamicanimation"
]