name: CI
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - '*'

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2.3.4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.3

  qodana:
    name: Qodana
    needs: [ validation ]
    runs-on: ubuntu-latest
    steps:
      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v2.0-eap
        with:
          project-dir: ../
          results-dir: ../build/qodana
          cache-dir: /home/runner/work/_temp/_github_home/qodana-cache

  lint:
    name: Lint
    needs: [ validation ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Save Gradle Caches
        uses: actions/cache@v2.1.5
        with:
          path: ~/.gradle/caches/
          key: gradle-caches-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-caches-${{ runner.os }}-
      - name: Lint
        run: ./gradlew lintAll
      - name: Stop Gradle
        run: ./gradlew --stop

  detekt:
    name: Detekt
    needs: [ validation ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Save Gradle Caches
        uses: actions/cache@v2.1.5
        with:
          path: ~/.gradle/caches/
          key: gradle-caches-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-caches-${{ runner.os }}-
      - name: Detekt
        run: ./gradlew detektAll
      - name: Stop Gradle
        run: ./gradlew --stop

  ktlint:
    name: ktlint
    needs: [ validation ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Save Gradle Caches
        uses: actions/cache@v2.1.5
        with:
          path: ~/.gradle/caches/
          key: gradle-caches-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-caches-${{ runner.os }}-
      - name: ktlint
        run: ./gradlew ktlintAll
      - name: Stop Gradle
        run: ./gradlew --stop

  cpd:
    name: CPD
    needs: [ validation ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Save Gradle Caches
        uses: actions/cache@v2.1.5
        with:
          path: ~/.gradle/caches/
          key: gradle-caches-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-caches-${{ runner.os }}-
      - name: CPD
        run: ./gradlew cpdAll
      - name: Stop Gradle
        run: ./gradlew --stop

  tests:
    name: Tests
    needs: [ validation, lint, detekt, ktlint, cpd ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Save Gradle Caches
        uses: actions/cache@v2.1.5
        with:
          path: ~/.gradle/caches/
          key: gradle-caches-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-caches-${{ runner.os }}-
      - name: Unit tests
        run: ./gradlew clean testDebugUnitTest
      - name: Stop Gradle
        run: ./gradlew --stop
      - name: Upload to Codecov
        uses: codecov/codecov-action@v1.4.1
