name: Experimental
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - '*'

jobs:
  detekt:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: JaCoCo
        run: ./gradlew jacocoTestReport
      - name: Stop Gradle
        run: ./gradlew --stop
      - name: Upload to Codecov
        uses: codecov/codecov-action@v1