name: Code analysis
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - '*'

jobs:
  checkout:
    name: Code checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
  analysis:
    needs: checkout
    name: Code analysis
    runs-on: ubuntu-latest
    steps:
      - name: Detekt
        run: ./gradlew detektAll
      - name: ktlint
        run: ./gradlew ktlintAll
      - name: CPD
        run: ./gradlew cpdAll
